export const AUTHENTICATION_STATES = {
  CHECKING_TOKEN: 'CHECKING_TOKEN',
  AUTHENTICATING:  'AUTHENTICATING',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  AUTHENTICATED: 'AUTHENTICATED'
};

export const APP_STATES = {
  INITIAL_LOAD: 'INITIAL_LOAD',
  REGISTER: 'REGISTER',
  REGISTER_GUEST: 'REGISTER_GUEST',
  LOGIN: 'LOGIN',
  GAME: 'GAME',
};

export const TOKEN_SAVE_KEY = 'LOS_AUTH_TOKEN';